import type { Lesson } from "../types";

export const sectionK3: Lesson[] = [
  {
    slug: "go-generate",
    title: "go generate directives",
    section: "K3",
    order: 59,
    body: `\`go generate\` runs commands specified by \`//go:generate\` comments.

- \`//go:generate stringer -type=Role\` generates \`String()\` for enum types.
- \`go generate ./...\` scans all packages for directives.
- Common generators: \`stringer\`, \`mockgen\`, \`protoc-gen-go\`, \`json-iterator/gen\`.
- Generated files should include a "DO NOT EDIT" comment and be committed to version control (usually).`,
    runMode: "terminal",
    terminalOutput: [{"kind":"command","text":"cat stringer.go"},{"kind":"stdout","text":"package main\n\n//go:generate stringer -type=Role\ntype Role int\n\nconst (\n    Reader Role = iota\n    Writer\n    Admin\n)"},{"kind":"command","text":"go generate ./..."},{"kind":"stdout","text":"# Runs go:generate directives in all .go files"},{"kind":"command","text":"cat role_string.go"},{"kind":"stdout","text":"// Code generated by stringer; DO NOT EDIT.\n// ..."},{"kind":"command","text":"# Common generators: stringer, mockgen, protoc-gen-go"}],
  },
  {
    slug: "go-env-vars",
    title: "go env, GOPATH, GOMODCACHE, GOPROXY, GOPRIVATE, GOFLAGS",
    section: "K3",
    order: 60,
    body: `Key environment variables:

- \`GOPATH\` — workspace root (defaults to \`$HOME/go\`).
- \`GOMODCACHE\` — cached modules (defaults to \`$GOPATH/pkg/mod\`).
- \`GOPROXY\` — module proxy chain (default: \`proxy.golang.org,direct\`).
- \`GOPRIVATE\` — patterns that bypass the proxy.
- \`GOFLAGS\` — default flags for \`go\` commands.`,
    runMode: "terminal",
    terminalOutput: [{"kind":"command","text":"go env GOPATH GOMODCACHE GOPROXY GOPRIVATE"},{"kind":"stdout","text":"/home/user/go\n/home/user/go/pkg/mod\nhttps://proxy.golang.org,direct\n"},{"kind":"command","text":"# GOPROXY controls where Go fetches modules from"},{"kind":"command","text":"GOPROXY=direct go mod tidy"},{"kind":"stdout","text":"# Fetches modules directly, bypassing the proxy"},{"kind":"command","text":"# GOPRIVATE bypasses the proxy for private repos"},{"kind":"command","text":"GOPRIVATE=github.com/myorg/* go mod tidy"},{"kind":"stdout","text":"# Downloads private modules directly"},{"kind":"command","text":"# GOFLAGS adds default flags to Go commands"},{"kind":"command","text":"GOFLAGS=-trimpath go build ."}],
  },
  {
    slug: "cross-compilation",
    title: "Cross compilation: GOOS/GOARCH, CGO_ENABLED",
    section: "K3",
    order: 61,
    body: `Go cross-compiles by setting \`GOOS\` and \`GOARCH\`:

- \`GOOS=linux GOARCH=amd64 go build\`: Linux x86-64 binary.
- \`GOOS=windows GOARCH=amd64 go build\`: Windows x86-64 binary.
- \`GOOS=darwin GOARCH=arm64 go build\`: macOS ARM binary.
- \`CGO_ENABLED=0\` produces a fully static binary (no libc dependency).
- \`go tool dist list\` shows all supported \`GOOS/GOARCH\` pairs.`,
    runMode: "terminal",
    terminalOutput: [{"kind":"command","text":"# List all supported platforms"},{"kind":"command","text":"go tool dist list | head -10"},{"kind":"stdout","text":"aix/ppc64\nandroid/386\nandroid/amd64\nandroid/arm\nandroid/arm64\ndarwin/amd64\ndarwin/arm64\ndragonfly/amd64\nfreebsd/386\nfreebsd/amd64"},{"kind":"command","text":"GOOS=linux GOARCH=amd64 go build -o app-linux-amd64 ."},{"kind":"stdout","text":""},{"kind":"command","text":"GOOS=windows GOARCH=amd64 go build -o app-windows-amd64.exe ."},{"kind":"stdout","text":""},{"kind":"command","text":"GOOS=darwin GOARCH=arm64 go build -o app-darwin-arm64 ."},{"kind":"stdout","text":""},{"kind":"command","text":"CGO_ENABLED=0 GOOS=linux go build -o app-static ."},{"kind":"command","text":"# CGO_ENABLED=0 produces a fully static binary"}],
  },
  {
    slug: "ldflags",
    title: "-ldflags (version stamping), -trimpath, build modes",
    section: "K3",
    order: 62,
    body: `\`-ldflags\` injects values at build time:

- \`-X main.version=1.2.3\`: set a \`var\` at link time.
- Common for version stamping: inject git tag, commit hash, build time.
- \`-trimpath\`: removes embedded local file paths from the binary (reproducible builds).
- Combine for CI: \`go build -trimpath -ldflags "-X main.version=$(git describe --tags)" .\`\``,
    runMode: "terminal",
    terminalOutput: [{"kind":"command","text":"cat main.go"},{"kind":"stdout","text":"package main\n\nimport \"fmt\"\n\nvar (\n    version   = \"dev\"\n    buildTime = \"unknown\"\n)\n\nfunc main() {\n    fmt.Printf(\"version: %s, built: %s\\n\", version, buildTime)\n}"},{"kind":"command","text":"go build -ldflags=\"-X main.version=1.2.3 -X main.buildTime=$(date -u +%Y%m%d%H%M%S)\" -o myapp ."},{"kind":"command","text":"./myapp"},{"kind":"stdout","text":"version: 1.2.3, built: 20250509120000"},{"kind":"command","text":"# -trimpath removes local paths from the binary"},{"kind":"command","text":"go build -trimpath -o myapp ."}],
  },
  {
    slug: "pprof-trace",
    title: "go tool pprof and go tool trace",
    section: "K3",
    order: 63,
    body: `Profiling tools:

- \`go test -cpuprofile\` / \`-memprofile\`: capture profiles during tests.
- \`go tool pprof\`: interactive top, list, web, flame graphs.
- \`go tool pprof -http=:8080 cpu.prof\`: web UI with flame graph.
- \`go test -trace\`: capture goroutine scheduling trace.
- \`go tool trace\`: visualize goroutine lifecycle, blocking, syscall timing.
- In production: \`net/http/pprof\` exposes profiles at \`/debug/pprof/\`.`,
    runMode: "terminal",
    terminalOutput: [{"kind":"command","text":"go test -cpuprofile=cpu.prof -memprofile=mem.prof ./..."},{"kind":"stdout","text":"PASS\nok  example.com/myapp  0.234s"},{"kind":"command","text":"go tool pprof cpu.prof"},{"kind":"stdout","text":"Type: cpu\nDuration: 0.23s\ntop\nShowing nodes accounting for 200ms, 100% of 200ms total\n      flat  flat%   sum%        cum   cum%\n     100ms 50.00% 50.00%      100ms 50.00%  myapp.HeavyWork\n     100ms 50.00%   100%      100ms 50.00%  runtime.memmove"},{"kind":"command","text":"# Interactive: 'top', 'list FuncName', 'web' (graphviz)"},{"kind":"command","text":"# Memory profiling:"},{"kind":"command","text":"go tool pprof mem.prof"},{"kind":"command","text":"# Execution tracer:"},{"kind":"command","text":"go test -trace=trace.out ./..."},{"kind":"command","text":"go tool trace trace.out"},{"kind":"stdout","text":"# Opens browser with goroutine scheduling visualization"}],
  }
];

export const sectionK3Checkpoint: Lesson["checkpoint"] = {
  "id": "checkpoint-k",
  "sectionSlug": "K1",
  "questions": [
    {
      type: "mcq",
      "prompt": "What does go mod tidy do?",
      "options": [
        "Installs all dependencies globally",
        "Adds missing deps and removes unused ones from go.mod",
        "Deletes the module cache",
        "Runs all tests"
      ],
      "correctIndex": 1,
      "explanation": "go mod tidy synchronizes go.mod with the actual imports, adding missing and removing unused dependencies."
    },
    {
      type: "mcq",
      "prompt": "What does go test -race detect?",
      "options": [
        "Memory leaks",
        "Data races (concurrent access without synchronization)",
        "Unused imports",
        "Compilation errors"
      ],
      "correctIndex": 1,
      "explanation": "go test -race enables the race detector, which finds unsynchronized concurrent access to shared data."
    },
    {
      type: "mcq",
      "prompt": "How do you cross-compile a Go program for Linux ARM64?",
      "options": [
        "go build --target=linux-arm64",
        "GOOS=linux GOARCH=arm64 go build",
        "go cross linux arm64",
        "go build -target linux/arm64"
      ],
      "correctIndex": 1,
      "explanation": "Go uses the GOOS and GOARCH environment variables for cross-compilation. No cross-compiler needed."
    },
    {
      type: "mcq",
      "prompt": "What does -ldflags '-X main.version=1.0' do?",
      "options": [
        "Sets a linker optimization flag",
        "Injects the value '1.0' into the variable main.version at build time",
        "Adds a command-line flag to the program",
        "Enables debug symbols"
      ],
      "correctIndex": 1,
      "explanation": "-X sets the value of a string variable at link time, commonly used for version stamping."
    },
    {
      type: "fill",
      "prompt": "Write the command to generate an HTML coverage report from coverage.out:",
      "acceptedAnswers": [
        "go tool cover -html=coverage.out",
        "go tool cover -html=coverage.out -o coverage.html"
      ],
      "explanation": "go tool cover -html reads a coverage profile and generates an HTML report showing which lines were covered."
    }
  ]
};
