import type { Lesson, TerminalLine } from '../types';

const lines: TerminalLine[] = [
  { kind: 'command', text: 'cat status.go' },
  { kind: 'stdout', text: `package status

//go:generate stringer -type=State

type State int

const (
	Idle State = iota
	Running
	Stopped
)
` },
  { kind: 'command', text: 'go install golang.org/x/tools/cmd/stringer@latest' },
  { kind: 'command', text: 'go generate ./...' },
  { kind: 'stdout', text: '' },
  { kind: 'command', text: 'cat state_string.go    # generated' },
  { kind: 'stdout', text: '// Code generated by "stringer -type=State"; DO NOT EDIT.\n\npackage status\n\nimport "strconv"\n\nfunc (i State) String() string { ... }\n' },
];

export const toolchainGenerate: Lesson = {
  slug: 'toolchain-generate',
  title: 'go generate — directive-driven codegen',
  sectionId: 'toolchain',
  order: 59,
  runMode: 'terminal',
  body: `\`go generate\` scans for \`//go:generate <command>\` directives in your sources and runs them. It's not part of \`go build\`; you run it explicitly when you want to regenerate. Common uses: \`stringer\` for enum-style types, \`mockgen\`, protobuf compilers, codegen for SQL.

Generated files should carry the \`Code generated … DO NOT EDIT.\` line on the first line; tools like \`go vet\` use it to skip them.`,
  terminalOutput: lines,
};
